apiVersion: v2
name: the-grid-playwright-synthetics
description: A wrapper Helm chart that deploys Playwright Synthetics
type: application
version: 0.1.0
appVersion: "0.88.1"
dependencies:
  - name: kube-prometheus-stack
    version: "81.4.3"
    repository: "https://prometheus-community.github.io/helm-charts" 
